import type { ItemInput } from '../types';

export const DEMO_ITEMS: ItemInput[] = [
  { name: 'Belgium Truffle', category: 'Small Cake Items', price: null },
  { name: 'Black Forest', category: 'Small Cake Items', price: null },
  { name: 'Blueberry', category: 'Small Cake Items', price: null },
  { name: 'Butter Scotch', category: 'Small Cake Items', price: null },
  { name: 'Choco Red Velvet Cake', category: 'Small Cake Items', price: null },
  { name: 'Creamy Cookies', category: 'Small Cake Items', price: null },
  { name: 'Creamy Sapphire', category: 'Small Cake Items', price: null },
  { name: 'Creamy Vanilla', category: 'Small Cake Items', price: null },
  { name: 'Dark Forest Cake', category: 'Small Cake Items', price: null },
  { name: 'Dual Forest Heart', category: 'Small Cake Items', price: null },
  { name: 'Dual Forest Round', category: 'Small Cake Items', price: null },
  { name: 'Dutch Choco', category: 'Small Cake Items', price: null },
  { name: 'Fresh Fruit', category: 'Small Cake Items', price: null },
  { name: 'IPL Cake', category: 'Small Cake Items', price: null },
  { name: 'Mango Cake', category: 'Small Cake Items', price: null },
  { name: 'Mothers Day Butterscotch Cake', category: 'Small Cake Items', price: null },
  { name: 'Mothers Day Sacher Cake', category: 'Small Cake Items', price: null },
  { name: 'New Pineapple', category: 'Small Cake Items', price: null },
  { name: 'Pinata', category: 'Small Cake Items', price: null },
  { name: 'Pineapple', category: 'Small Cake Items', price: null },
  { name: 'Red Velvet Heart', category: 'Small Cake Items', price: null },
  { name: 'Sacher Delight', category: 'Small Cake Items', price: null },
  { name: 'Sacher Heart', category: 'Small Cake Items', price: null },
  { name: 'White Forest Premium', category: 'Small Cake Items', price: null },

  { name: 'Almond Dutch Pastry', category: 'Pastries Items', price: null },
  { name: 'Black Forest Pastry', category: 'Pastries Items', price: null },
  { name: 'Blueberry Fruitfill Pastry', category: 'Pastries Items', price: null },
  { name: 'Brownie Square Pastry', category: 'Pastries Items', price: null },
  { name: 'Butter Scotch Pastry', category: 'Pastries Items', price: null },
  { name: 'Choco Lava', category: 'Pastries Items', price: null },
  { name: 'Choco Mud', category: 'Pastries Items', price: null },
  { name: 'Chocolate Mousse', category: 'Pastries Items', price: null },
  { name: 'Cocktail Pastry', category: 'Pastries Items', price: null },
  { name: 'Fruit Custard', category: 'Pastries Items', price: null },
  { name: 'Hazelnut Pastry', category: 'Pastries Items', price: null },
  { name: 'Honey Anjeer Pastry', category: 'Pastries Items', price: null },
  { name: 'Kulfi Pista Pastry', category: 'Pastries Items', price: null },
  { name: 'Mango Pastry', category: 'Pastries Items', price: null },
  { name: 'Mousumi Pastry', category: 'Pastries Items', price: null },
  { name: 'Pineapple Veg Pastry', category: 'Pastries Items', price: null },
  { name: 'Red Velvet Cheese Pastry', category: 'Pastries Items', price: null },
  { name: 'Rich Coffee Pastry', category: 'Pastries Items', price: null },
  { name: 'Rose Cheese Pastry', category: 'Pastries Items', price: null },
  { name: 'Salted Caramel Pastry', category: 'Pastries Items', price: null },
  { name: 'Truffle Delight Pastry', category: 'Pastries Items', price: null },
  { name: 'Vanilla Tuti Fruti Pastry', category: 'Pastries Items', price: null },

  { name: 'Chicken Cheese Kabab', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Chicken Chettinad Sub', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Chicken Claw', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Chicken Creamy Roll', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Chicken Cutlet', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Chicken Hotdog', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Chicken Keema Roll', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Chicken Net Puff', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Chicken Puff', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Chicken Sandwich', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Chicken Tikka Pizza', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Chicken Tikka Sandwich', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Chicken Tikka Sub', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Creamy Chicken Roll', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Egg Puff', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Fried Chicken Burger', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Hariyali Chicken Sub', category: 'Non-Veg Savouries Items', price: null },
  { name: 'IPL Non-Veg Combo', category: 'Non-Veg Savouries Items', price: null },
  { name: 'Lemon Chicken Envelope', category: 'Non-Veg Savouries Items', price: null },

  { name: 'Brown Bread', category: 'Veg Savouries Items', price: null },
  { name: 'Chilli Paneer Roll', category: 'Veg Savouries Items', price: null },
  { name: 'Creamy Mushroom Roll', category: 'Veg Savouries Items', price: null },
  { name: 'Doughnuts Bread', category: 'Veg Savouries Items', price: null },
  { name: 'Doughnuts Choco Bread', category: 'Veg Savouries Items', price: null },
  { name: 'Hara Bhara Kebab Sub', category: 'Veg Savouries Items', price: null },
  { name: 'IPL Veg Combo', category: 'Veg Savouries Items', price: null },
  { name: 'Malai Paneer Sub', category: 'Veg Savouries Items', price: null },
  { name: 'Milk Bread', category: 'Veg Savouries Items', price: null },
  { name: 'Mushroom Puff', category: 'Veg Savouries Items', price: null },
  { name: 'Paneer Claws', category: 'Veg Savouries Items', price: null },
  { name: 'Paneer Tikka Pizza', category: 'Veg Savouries Items', price: null },
  { name: 'Paneer Tikka Sandwich', category: 'Veg Savouries Items', price: null },
  { name: 'Paneer Finger', category: 'Veg Savouries Items', price: null },
  { name: 'Paneer Puff', category: 'Veg Savouries Items', price: null },
  { name: 'Papdi Paneer', category: 'Veg Savouries Items', price: null },
  { name: 'Veg Burger', category: 'Veg Savouries Items', price: null },
  { name: 'Veg Cheese Kabab', category: 'Veg Savouries Items', price: null },
  { name: 'Veg Cutlet', category: 'Veg Savouries Items', price: null },
  { name: 'Veg Manchurian', category: 'Veg Savouries Items', price: null },
  { name: 'Veg Patties', category: 'Veg Savouries Items', price: null },
  { name: 'Veg Sandwich', category: 'Veg Savouries Items', price: null },
  { name: 'Veg Spring Roll', category: 'Veg Savouries Items', price: null },
];
